site_name: DevOps Cheatsheets
site_url: https://laurenx122.github.io/work.cheat-sheets/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Home: index.md
  - CKAD: ckad-cheatsheet.md
  - AWS-EKS: aws-eks-cheatsheet.md